version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    day: sunday
    interval: weekly
- package-ecosystem: docker
  directory: /
  schedule:
    day: sunday
    interval: weekly
- package-ecosystem: gomod
  directory: /
  schedule:
    day: sunday
    interval: weekly
- package-ecosystem: gomod
  directory: /internal/tools
  schedule:
    day: sunday
    interval: weekly
- package-ecosystem: gomod
  directory: /offsets-tracker
  schedule:
    day: sunday
    interval: weekly
