kernel="ghcr.io/cilium/ci-kernels:stable"
smp="cpus=4"
memory="8G"
user="root"
setup=[
   "mount -t cgroup2 -o nosuid,noexec,nodev cgroup2 /sys/fs/cgroup",
   "/bin/sh -c 'modprobe bpf_testmod || true'",
   "dmesg --clear",
]
teardown=[
   "dmesg --read-clear",
]