apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sample-app.fullname" . }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sample-app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      shareProcessNamespace: true
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh",  "-c"]
          args: ["(/sample-app/start.sh || /sample-app/main) && kill -TERM $(pidof otel-go-instrumentation)"]
        - name: auto-instrumentation
          image: otel-go-instrumentation
          imagePullPolicy: IfNotPresent
          command: ["/otel-go-instrumentation", "-global-impl", "-log-level=debug"]
          env:
          - name: OTEL_GO_AUTO_TARGET_EXE
            value: /sample-app/main
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://test-opentelemetry-collector:4318"
          - name: OTEL_SERVICE_NAME
            value: "sample-app"
          - name: OTEL_PROPAGATORS
            value: "tracecontext,baggage"
          - name: OTEL_GO_AUTO_INCLUDE_DB_STATEMENT
            value: "true"
          - name: OTEL_BSP_SCHEDULE_DELAY
            value: "60000"
          resources: {}
          securityContext:
            runAsUser: 0
            privileged: true
          volumeMounts:
          - mountPath: /sys/kernel/debug
            name: kernel-debug
      volumes:
      - name: kernel-debug
        hostPath:
          path: /sys/kernel/debug
