name: New Instrumentation
about: Request new instrumentation be added to the project
title: 'New Instrumentation Request for <PACKAGE>'
labels:
  - enhancement
  - new instrumentation
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new instrumentation request!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: |
        Please search to see if an issue already exists for the instrumentation.
  
        If one already exists, add a 👍 to that issue and your use-case if it is not already captured.
      options:
      - label: I have searched the existing issues
  - type: textarea
    attributes:
      label: Package
      description: What is the name of the Go package?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Version
      description: What version of the package do you use?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: How do you normally run applications built with the package?
      placeholder: As a Deployment on Kubernetes 1.30
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use-case
      description: What kind of applications do you build with the package?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Telemetry
      description: What telemetry you would like to see for for the package?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context!
  
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
