name: codespell
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Codespell
        run: make codespell
