name: codespell
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Codespell
        run: make codespell
