name: Automation - Dependabot PR

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install zsh
        run: sudo apt-get update; sudo apt-get install zsh

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "~1.21.2"
          check-latest: true

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y clang llvm libbpf-dev

      - name: Run dependabot-pr.sh
        run: ./.github/workflows/scripts/dependabot-pr.sh
        env:
          GITHUB_TOKEN: ${{ secrets.OPENTELEMETRYBOT_GITHUB_TOKEN }}
