name: Links (Fail Fast)

on:
  push:
    branches:
      - main
  pull_request:

# Declare default permissions as read only.
permissions: read-all

jobs:
  check-links:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Restore lychee cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        id: cache-restore
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}

      - name: Link Checker
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail: true
          args: >
            --verbose
            --no-progress
            --max-concurrency 5
            --max-retries 6
            --retry-wait-time 2
            --cache
            --max-cache-age 1d
            --cache-exclude-status 300..=599
            "**/*.md"

      - name: Save lychee cache
        if: always()
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: .lycheecache
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
