name: Automatic Offset Generation
on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  updateOffsets:
    permissions:
      contents: write # required for pushing changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: stable
          check-latest: true
          cache-dependency-path: "**/go.sum"

      - name: Update offsets
        run: make offsets

      - name: generate token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate-token
        with:
          client-id: ${{ vars.OTELBOT_CLIENT_ID }}
          private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}

      - name: "Create/update PR"
        env:
          # Not using secrets.GITHUB_TOKEN since pull requests from that token
          # do not run workflows.
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          message="Automatic update of offsets.json"
          body="The offsets have been updated by go-offsets-tracker"
          branch="otelbot/offset-content-auto-update"

          git config user.name otelbot
          git config user.email 197425009+otelbot@users.noreply.github.com

          git checkout -b $branch
          git commit -a -m "$message"
          git push --set-upstream origin $branch
          gh pr create --title "$message" \
                       --body "$body" \
                       --base main
